name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: devopsacr962
  IMAGE_NAME: devops-static-site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group devops-rg --name devops-aks --overwrite-existing

      - name: Attach ACR to AKS
        run: az aks update -n devops-aks -g devops-rg --attach-acr ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Deploy to AKS
        run: |
          kubectl create deployment devops-static-site --image=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest --dry-run=client -o yaml | kubectl apply -f -
          kubectl set image deployment/devops-static-site devops-static-site=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          kubectl expose deployment devops-static-site --type=LoadBalancer --port=80 --target-port=80 --dry-run=client -o yaml | kubectl apply -f -
          kubectl rollout status deployment/devops-static-site
